name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: [started]

jobs:

  build-latest:

    runs-on: ubuntu-latest

    - name: get jd_wstool
      run: |
           wget https://github.com/yqchilde/JDMemberCloseAccount/releases/download/v1.0.3/jd_wstool-linux-amd64.tar.gz
           tar -zxvf jd_wstool-linux-amd64.tar.gz
           pwd
           ls

    - name: get chrome
      run: |
           wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_95.0.4638.54-1_amd64.deb
           pwd
           ls

    - name: get chromedriver
      run: |
           wget http://chromedriver.storage.googleapis.com/95.0.4638.54/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
           mv chromedriver drivers/chromedriver
           pwd
           ls

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           pwd
           ls
           docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jdmc:amd64
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker push ${{ secrets.DOCKER_USERNAME }}/jdmc:amd64