name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: [started]

jobs:

  build-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get jd_wstool
      run: |
           sudo rm -rf jd_wstool
           wget https://github.com/yqchilde/JDMemberCloseAccount/releases/download/v1.0.3/jd_wstool-linux-amd64.tar.gz
           tar -zxvf jd_wstool-linux-amd64.tar.gz
           rm jd_wstool-linux-amd64.tar.gz

    - name: get chrome
      run: |
           wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_95.0.4638.54-1_amd64.deb

    - name: get chromedriver
      run: |
           wget http://chromedriver.storage.googleapis.com/95.0.4638.54/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
           mv chromedriver drivers/chromedriver
           rm chromedriver_linux64.zip

    - name: Build the Docker jdmc
      run: |
           docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/jdmc
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker push ${{ secrets.DOCKER_USERNAME }}/jdmc

    - name: Build the Docker tool
      run: |
           docker build . --file Dockerfile2 --tag ${{ secrets.DOCKER_USERNAME }}/jdmc:tool
           docker push ${{ secrets.DOCKER_USERNAME }}/jdmc:tool

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 10